### ISSUE TITLE
App not desplaying correctly

### ISSUE THREAD

**Issue by GingerGuy118** [Shinyhero36/Spicetify-Taste-Analyzer#14]
I have downloaded the extension from GitHub and yet when opened in Spotify, the pictures of the artists are very large and only 1 is displayed every row. It looks nothing like the preview although I used Dribblish Nord.
Spotify version: 1.1.84.716.gc5f8b819
OS: Windows
Spiceify Version: 2.9.8

**Comment by Shinyhero36** [comment]
That's because the CSS is broken, i'll fix it

**Comment by Shinyhero36** [comment]
I fixed the issue. You can reinstall the custom-app from the master branch
