### ISSUE TITLE
Installing the Program after getting the repository./ "make" does not work

### ISSUE THREAD

**Issue by splorux25** [Shinyhero36/Spicetify-Taste-Analyzer#3]
If i try to execute the make command it gives me this error.
Thanks in advance.
![image](https://user-images.githubusercontent.com/77694883/140656736-fe45dc5b-0f85-4025-9af3-f7236d467dda.png)

**Comment by turquoise-turtle** [comment]
I found I could just drag the entire folder into .spicetify/CustomApps, run `spicetify config custom_apps Spicetify-Taste-Analyzer-master` (or whatever the folder is named), and then run `spicetify apply`.
