### ISSUE TITLE
Wierd "Your Top Genre" Display

### ISSUE THREAD

**Issue by seniorkiller** [Shinyhero36/Spicetify-Taste-Analyzer#7]
**Description**
not sure how to describe it. see the picture below.

**Additional Info**
not sure what causing it. haven't been able to make it work. i've tried change to default theme and disable all the patch and experimental feature and nothing change.

**Some Info**
OS: Linux v5.15.22-1-lts
Spotify: v1.1.72.439
Spicetify: v2.9.0
Theme: dribbblish-dynamic

**Attachment**
![image](https://user-images.githubusercontent.com/77882062/153800209-c3e9f74c-df90-4016-a7bc-862a6920756f.png)

**Comment by Shinyhero36** [comment]
Are you using the default theme or dribblish-dynamic in this picture?

If your are using the deafult one, the only workaround I've found for now is to go to the Search tab and go back to this page.

**Comment by seniorkiller** [comment]
the picture is using default one, but i usually using dribblish-dynamic. the picture i taken when i trying to make it work. at first i thought it was dribblish-dynamic that break it.

**Comment by seniorkiller** [comment]
i tried going to the search tab and back but it didn't work(default theme). ive tried using dribblish theme too but is the same as dynamic one

**Comment by Shinyhero36** [comment]
> i have couple other extension enabled tho. dont know it somewhat affect it

It might be possible but I have a lot of extensions. I don't think this is what breaks the UI.

**My config:**
OS: Windows v10.0.19042
Spotify: v1.1.78.765
Spicetify: v2.9.0
Dribbblish: v4.1.1-0e50a92

Anyway, I'll try to replicate this issue on my linux machine

**Comment by Shinyhero36** [comment]
Ok, I have the same issue on my linux machine.
I'll try to fix it and reach out to you soon

**Comment by seniorkiller** [comment]
Ok thanks for the quick response

**Comment by Shinyhero36** [comment]
Are you running the latest version of spotify on your machine?

**Comment by seniorkiller** [comment]
it solve by the new update.
